[workspace]
resolver = "3"
members = [
	"bobcat-maths",
	"bobcat-storage",
	"bobcat-entry",
	"bobcat-panic",
	"bobcat-proxy",
	"bobcat-cd",
	"bobcat-sdk"
]
exclude = ["fuzz"]

[workspace.dependencies]
proptest = { version = "1.8.0" }
const-hex = { version = "1.16.0", default-features = false }
array-concat = "0.5.5"
