// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	Wallet  string `json:"wallet"`
	Content string `json:"content"`
}

type Mutation struct {
}

type Query struct {
}
