// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	Content string `json:"content"`
	TxHash  string `json:"txHash"`
}

type Mutation struct {
}

type Query struct {
}
