[package]
name = "mul-div"
version = "0.6.0"
edition = "2024"

[dependencies]
alloy-primitives = { version = "1.4.1", default-features = false }
bobcat-sdk.workspace = true
mini-alloc.workspace = true
ruint = { version = "1.17.0", default-features = false }

[[bin]]
name = "mul-div"
path = "src/main.rs"
