[package]
name = "bobcat-maths-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "0.4", features = ["arbitrary-derive"] }
ruint = { version = "1.12.4" }

[dependencies.bobcat-maths]
path = "../bobcat-maths"
features = ["arbitrary-enabled", "alloc", "alloy-enabled"]

[[bin]]
name = "add"
path = "fuzz_targets/add.rs"
test = false
doc = false
bench = false

[[bin]]
name = "sub"
path = "fuzz_targets/sub.rs"
test = false
doc = false
bench = false

[[bin]]
name = "mul"
path = "fuzz_targets/mul.rs"
test = false
doc = false
bench = false

[[bin]]
name = "div"
path = "fuzz_targets/div.rs"
test = false
doc = false
bench = false
