[package]
name = "reference-widening-mul"
version = "0.1.11"
edition = "2024"

[dependencies]
alloy-primitives = { version = "=0.8.20", default-features = false }

[[bin]]
name = "reference_widening_mul"
path = "src/main.rs"

[profile.release]
codegen-units = 1
strip = true
lto = true
panic = "abort"
opt-level = "z"
