[workspace]
resolver = "3"
members = [
    "001-counter",
    "002-mul_div",
    "003-beacon",
    "004-calling",
    "005-layerzero",
    "006-camelot-swapping"
]

[workspace.dependencies]
bobcat-sdk = { path = "../bobcat-sdk" }

[profile.release]
codegen-units = 1
strip = true
lto = true
panic = "abort"
opt-level = "s"
