[workspace]

[package]
name = "bobcat-examples-004-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "0.4", features = ["arbitrary-derive"] }

[dependencies.bobcat-examples-004]
path = ".."
features = ["std", "arbitrary", "inline-maths"]

[[bin]]
name = "storage"
path = "fuzz_targets/storage.rs"
test = false
doc = false
bench = false
