[workspace]
resolver = "3"
members = ["chainlink-vrf-test", "console-log-txt", "transient-exchange"]

[workspace.dependencies]
bobcat-sdk = { path = "../bobcat-sdk", features = ["panic", "alloc"] }
mini-alloc = "1.0.0"

[profile.release]
codegen-units = 1
strip = true
lto = true
panic = "abort"
opt-level = "z"
