[package]
name = "bobcat-create"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Bobcat SDK utilities for using CREATE1 and CREATE2 on Arbitrum Stylus."
homepage = "https://bobcat.so"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[lib]
name = "bobcat_create"

[dependencies]
bobcat-proxy = { path = "../bobcat-proxy" }
bobcat-maths = { path = "../bobcat-maths" }

[features]
alloc = []
std = ["alloc"]
