[package]
name = "bobcat-sdk"
version = "0.4.0"
edition = "2024"
license = "MIT"
description = "Bobcat SDK is a codesize efficent SDK for developing on Arbitrum Stylus."
homepage = "https://bobcat.so"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[lib]
name = "bobcat_sdk"

[dependencies]
bobcat-create = { version = "0.4.0", path = "../bobcat-create" }
bobcat-entry = { version = "0.4.0", path = "../bobcat-entry" }
bobcat-maths = { version = "0.4.0", path = "../bobcat-maths" }
bobcat-panic = { version = "0.4.0", path = "../bobcat-panic", optional = true }
bobcat-proxy = { version = "0.4.0", path = "../bobcat-proxy" }
bobcat-storage = { version = "0.4.0", path = "../bobcat-storage" }
bobcat-cd = { version = "0.4.0", path = "../bobcat-cd" }
bobcat-interfaces = { version = "0.4.0", path = "../bobcat-interfaces" }
bobcat-call = { version = "0.4.0", path = "../bobcat-call" }

[features]
std = [
	"bobcat-create/std",
	"bobcat-entry/std",
	"bobcat-maths/std",
	"bobcat-panic/std",
	"bobcat-storage/std",
]
borsh = ["bobcat-maths/borsh"]
alloc = [
	"bobcat-create/alloc",
	"bobcat-entry/alloc",
	"bobcat-maths/alloc",
	"bobcat-panic/alloc",
]
arbitrary-enabled = ["bobcat-maths/arbitrary-enabled"]
proptest-enabled = ["bobcat-maths/proptest-enabled"]
panic = ["bobcat-panic"]
dont-define-symbols = ["bobcat-entry/dont-define-symbols"]
